# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
  secret_key_base: 3c08da13a8ffc0190257d5f2bf69af0bd81a26735fff818c7c139609d3c5408fc7cfab222b734f448da7cdcb5f75a95ace3d3978fec4fa41dc74eedeb122d9db
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  publishable_key: <%= ENV['PUBLISHABLE_KEY'] %>
  secret_key: <%= ENV['SECRET_KEY'] %>



test:
  secret_key_base: eaba4edb1320cc0ea082d8063d1ade62eeac38d62d0a2fdee3a46be1c33d30860bcc30f16d162323d1d7b1d1e61d8eaaeb4a4ca9fec3038a6537be3d5e83c097

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>

 

